import type { WidgetDefinition, WidgetId } from './types';

export const WIDGET_REGISTRY: Record<WidgetId, WidgetDefinition> = {
  'ops-hero-kpi-strip': {
    id: 'ops-hero-kpi-strip',
    name: 'Ops hero KPIs',
    description: 'In store now, peak occupancy, typical shoppers, avg wait',
    kind: 'kpi',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsOps: true,
  },
  'ops-alerts-panel': {
    id: 'ops-alerts-panel',
    name: 'Ops alerts',
    description: 'Severity-ranked operational alerts',
    kind: 'insight',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsOps: true,
  },
  'ops-store-activity-chart': {
    id: 'ops-store-activity-chart',
    name: 'Store activity chart',
    description: 'Hourly/daily peak shoppers or footfall with range brush',
    kind: 'chart',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsOps: true,
  },
  'ops-footfall-by-hour': {
    id: 'ops-footfall-by-hour',
    name: 'Footfall by open hour',
    description: 'Entrance visits (or occupancy) by hour of day',
    kind: 'chart',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 8, rowSpan: 2 },
    needsOps: true,
  },
  'reporting-kpi-strip': {
    id: 'reporting-kpi-strip',
    name: 'Persona KPI strip',
    description: 'Horizontal strip of reporting KPIs',
    kind: 'kpi',
    sources: ['Shelf & Category', 'PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
  },
  'reporting-insights-panel': {
    id: 'reporting-insights-panel',
    name: 'Threshold insights',
    description: 'Critical / warn / success from KPI thresholds',
    kind: 'insight',
    sources: ['Shelf & Category', 'PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'exec-store-health-pillars': {
    id: 'exec-store-health-pillars',
    name: 'Store health pillars',
    description: 'Traffic · Ops · Merch · Media',
    kind: 'kpi',
    sources: ['Executive Summary'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
  },
  'exec-highlight-chips': {
    id: 'exec-highlight-chips',
    name: 'Executive highlights',
    description: 'Best zone, top category, top campaign',
    kind: 'insight',
    sources: ['Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 1 },
  },
  'category-visits-panel': {
    id: 'category-visits-panel',
    name: 'Category traffic bars',
    description: 'Visits and dwell by category',
    kind: 'chart',
    sources: ['Operations Pulse', 'Shelf & Category', 'Executive Summary', 'Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'zone-performance-map': {
    id: 'zone-performance-map',
    name: 'Zone performance map',
    description: 'Floor plan with underperform / top ROI zones',
    kind: 'map',
    sources: ['Shelf & Category', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    isMap: true,
  },
  'peble-screen-campaign-map': {
    id: 'peble-screen-campaign-map',
    name: 'Screen & campaign map',
    description: 'DOOH markers with CES / EAL',
    kind: 'map',
    sources: ['PEBLE'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    isMap: true,
  },
  'campaign-ranking-table': {
    id: 'campaign-ranking-table',
    name: 'Campaign ranking',
    description: 'CES, EAL, AAR, exposures',
    kind: 'table',
    sources: ['PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'exec-header-headline': {
    id: 'exec-header-headline',
    name: 'Esselunga headline',
    description: 'Verdict sentence + headline KPIs',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
  },
  'exec-action-insights': {
    id: 'exec-action-insights',
    name: 'What to act on',
    description: 'Severity cards with recommended actions',
    kind: 'insight',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
  },
  'activity-timeline-chart': {
    id: 'activity-timeline-chart',
    name: 'Store rhythm',
    description: 'Entrants or shelf stops over time (toggle, own Y-scale)',
    kind: 'chart',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
  },
  'floor-visual-toggle': {
    id: 'floor-visual-toggle',
    name: 'Floor visual (heatmap | flow)',
    description: '3D heatmap or people-flow field with mode toggle',
    kind: 'map',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 3 },
    isMap: true,
    needsJourney: true,
  },
  'journey-signals-panel': {
    id: 'journey-signals-panel',
    name: 'Entrance signals',
    description: 'Entrants · shelf engagement · checkout',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
  },
  'fresco-department-cards': {
    id: 'fresco-department-cards',
    name: 'Piazza del Fresco cards',
    description: 'Per-counter stopping and dwell',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsJourney: true,
  },
  'aisle-stat-stack': {
    id: 'aisle-stat-stack',
    name: 'Aisle summary stats',
    description: 'Stopping / engagement / pass-through / bypass',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
  },
  'checkout-panel': {
    id: 'checkout-panel',
    name: 'Checkout channels',
    description: 'Wait, abandon, friction by channel',
    kind: 'table',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
  },
  'media-ring-gauges': {
    id: 'media-ring-gauges',
    name: 'Retail media gauges',
    description: 'CES and EAL ring gauges',
    kind: 'chart',
    sources: ['Esselunga Executive', 'PEBLE'],
    defaultSize: { colSpan: 4, rowSpan: 1 },
    needsJourney: true,
  },
};

export const ALL_WIDGETS: WidgetDefinition[] = Object.values(WIDGET_REGISTRY);

export function getWidget(id: WidgetId): WidgetDefinition {
  return WIDGET_REGISTRY[id];
}
