import type { WidgetDefinition, WidgetId } from './types';

export const WIDGET_REGISTRY: Record<WidgetId, WidgetDefinition> = {
  'ops-hero-kpi-strip': {
    id: 'ops-hero-kpi-strip',
    name: 'Ops hero KPIs',
    description: 'In store now, peak occupancy, typical shoppers, avg wait',
    kind: 'kpi',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsOps: true,
  },
  'ops-alerts-panel': {
    id: 'ops-alerts-panel',
    name: 'Ops alerts',
    description: 'Severity-ranked operational alerts',
    kind: 'insight',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsOps: true,
  },
  'ops-store-activity-chart': {
    id: 'ops-store-activity-chart',
    name: 'Store activity chart',
    description: 'Hourly/daily peak shoppers or footfall with range brush',
    kind: 'chart',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsOps: true,
  },
  'ops-footfall-by-hour': {
    id: 'ops-footfall-by-hour',
    name: 'Footfall by open hour',
    description: 'Entrance visits (or occupancy) by hour of day',
    kind: 'chart',
    sources: ['Operations Pulse'],
    defaultSize: { colSpan: 8, rowSpan: 2 },
    needsOps: true,
  },
  'reporting-kpi-strip': {
    id: 'reporting-kpi-strip',
    name: 'Persona KPI strip',
    description: 'Horizontal strip of reporting KPIs',
    kind: 'kpi',
    sources: ['Shelf & Category', 'PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
  },
  'reporting-insights-panel': {
    id: 'reporting-insights-panel',
    name: 'Threshold insights',
    description: 'Critical / warn / success from KPI thresholds',
    kind: 'insight',
    sources: ['Shelf & Category', 'PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'exec-store-health-pillars': {
    id: 'exec-store-health-pillars',
    name: 'Store health pillars',
    description: 'Traffic · Ops · Merch · Media',
    kind: 'kpi',
    sources: ['Executive Summary'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
  },
  'exec-highlight-chips': {
    id: 'exec-highlight-chips',
    name: 'Executive highlights',
    description: 'Best zone, top category, top campaign',
    kind: 'insight',
    sources: ['Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 1 },
  },
  'category-visits-panel': {
    id: 'category-visits-panel',
    name: 'Category traffic bars',
    description: 'Visits and dwell by category',
    kind: 'chart',
    sources: ['Operations Pulse', 'Shelf & Category', 'Executive Summary', 'Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'zone-performance-map': {
    id: 'zone-performance-map',
    name: 'Zone performance map',
    description: 'Floor plan with underperform / top ROI zones',
    kind: 'map',
    sources: ['Shelf & Category', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    isMap: true,
  },
  'peble-screen-campaign-map': {
    id: 'peble-screen-campaign-map',
    name: 'Screen & campaign map',
    description: 'DOOH markers with CES / EAL',
    kind: 'map',
    sources: ['PEBLE'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    isMap: true,
  },
  'campaign-ranking-table': {
    id: 'campaign-ranking-table',
    name: 'Campaign ranking',
    description: 'CES, EAL, AAR, exposures',
    kind: 'table',
    sources: ['PEBLE', 'Executive Summary'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
  },
  'exec-header-headline': {
    id: 'exec-header-headline',
    name: 'Esselunga headline (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
    legacy: true,
  },
  'exec-action-insights': {
    id: 'exec-action-insights',
    name: 'What to act on (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'insight',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
    legacy: true,
  },
  'activity-timeline-chart': {
    id: 'activity-timeline-chart',
    name: 'Store rhythm (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'chart',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
    legacy: true,
  },
  'floor-visual-toggle': {
    id: 'floor-visual-toggle',
    name: 'Floor visual (heatmap | flow) (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'map',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 3 },
    isMap: true,
    needsJourney: true,
    legacy: true,
  },
  'journey-signals-panel': {
    id: 'journey-signals-panel',
    name: 'Entrance signals (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
    legacy: true,
  },
  'fresco-department-cards': {
    id: 'fresco-department-cards',
    name: 'Piazza del Fresco cards (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsJourney: true,
    legacy: true,
  },
  'aisle-stat-stack': {
    id: 'aisle-stat-stack',
    name: 'Aisle summary stats (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'kpi',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsJourney: true,
    legacy: true,
  },
  'checkout-panel': {
    id: 'checkout-panel',
    name: 'Checkout channels (legacy)',
    description: 'Calcolo precedente, basato su zone_visits / queue_sessions. Da dismettere.',
    kind: 'table',
    sources: ['Esselunga Executive'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsJourney: true,
    legacy: true,
  },
  'media-ring-gauges': {
    id: 'media-ring-gauges',
    name: 'Retail media gauges',
    description: 'CES and EAL ring gauges',
    kind: 'chart',
    sources: ['Esselunga Executive', 'PEBLE'],
    defaultSize: { colSpan: 4, rowSpan: 1 },
    needsJourney: true,
  },
  'esselunga-headline-v2': {
    id: 'esselunga-headline-v2',
    name: 'Esselunga headline',
    description: 'Ingressi, durata visita, presenze, attesa in coda da daily_kpi',
    kind: 'kpi',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 12, rowSpan: 1 },
    needsDailyKpi: true,
  },
  'store-rhythm-v2': {
    id: 'store-rhythm-v2',
    name: 'Ritmo della giornata',
    description: 'Ingressi per fascia (raw LiDAR)',
    kind: 'chart',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'department-minutes': {
    id: 'department-minutes',
    name: 'Minuti per reparto',
    description: 'Minuti per cliente per dipartimento (Little)',
    kind: 'chart',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 12, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'queue-by-lane': {
    id: 'queue-by-lane',
    name: 'Coda per cassa',
    description: 'WAITING / TRANSIT / FIXED per corsia',
    kind: 'table',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'queue-by-slot': {
    id: 'queue-by-slot',
    name: 'Coda per fascia',
    description: 'Attesa vs servizio per fascia oraria',
    kind: 'chart',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'first-department': {
    id: 'first-department',
    name: 'Primo reparto',
    description: 'Primo reparto dopo l’ingresso',
    kind: 'chart',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'behaviour-mix': {
    id: 'behaviour-mix',
    name: 'Mix comportamentale',
    description: '7 modi (120) — non calcolato se il job è troppo pesante',
    kind: 'chart',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsDailyKpi: true,
  },
  'daily-checks': {
    id: 'daily-checks',
    name: 'Controlli del giorno',
    description: 'Little, fantasmi, ROI scoperti, buchi del flusso',
    kind: 'insight',
    sources: ['daily-kpi'],
    defaultSize: { colSpan: 6, rowSpan: 2 },
    needsDailyKpi: true,
  },
};

export const ALL_WIDGETS: WidgetDefinition[] = Object.values(WIDGET_REGISTRY);

export function getWidget(id: WidgetId): WidgetDefinition {
  return WIDGET_REGISTRY[id];
}
